### ISSUE TITLE
Desktop Safari styles are broken

### ISSUE THREAD

**Issue by obenjiro** [tenphi/nude#1]
Open link https://jsbin.com/neteqas/edit?html,output in  Desktop Safari 

<img width="826" alt="Снимок экрана 2019-07-29 в 13 31 31" src="https://user-images.githubusercontent.com/1760346/62041829-442ea900-b205-11e9-99dc-cf5c6430e1f4.png">

**Comment by timeshift92** [comment]
this is because zhsbin could not import css

**Comment by tenphi** [comment]
Thanks! We will create our own Playground soon. Issue you mentioned is only reproduced on the jsbin site. Something is broken in their build system.
