### ISSUE TITLE
Support for older browsers

### ISSUE THREAD

**Issue by LeonidYarosh** [tenphi/nude#2]
Hi! Cool application. I would like to have support for older browsers, below IE11, where there is no support for Custom Properties and Custom Elements. What do you think about this?

Landing page are often required for small customers who need to work on all browsers. And making up the old fashioned way is a little boring)

**Comment by tenphi** [comment]
Thanks for the request. It is possible to create NUDE version that will support IE11, but there is no plans to create such version. But anyone who decided to do so will receive a great amount of help from me.
Older IE versions can't be polyfilled to support Custom Elements, so there is no change to migrate Nude to such old browsers. But there is still a possibility to create NuML server-side preprocessor for static sites (landings for example). It would be a tough tasks and some features will be missing, but it's possible.

Anyway, such preprocessor (but for the newer browsers) is in the roadmap. Maybe when it's ready it will motivate developers in enhance it for the older browsers.
